### ISSUE TITLE
Error: No valid exports main found 

### ISSUE THREAD

**Issue by MKahacker** [jridgewell/gen-mapping#7]
Started getting this weird error when I run `react-native run-ios` in my project. It just started happening all of a sudden and I haven't been able to find the root cause.

I tried removing my `node_modules` and re-installing multiple times. Also cleaned my yarn cache `yarn cache clean` and removed temp react and metro files `rm -rf $TMPDIR/react-*` and `rm -rf $TMPDIR/metro-*`. I also tried to clear my xcode build directory for the project but that didn't help. Also cleared watch man `watchman watch-del-all`. 
 
So far none of these have helped I see the `@jridgewell/gen-mapping` directory in my node_modules file so I am not sure what the issue is here.
<img width="346" alt="Screenshot 2023-04-02 at 1 34 17 PM" src="https://user-images.githubusercontent.com/23608041/229377701-efd246e8-efd1-4411-99e5-7d8a319b4e50.png">

  
The error:
```

internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for '/Users/user/project/node_modules/@jridgewell/gen-mapping'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/project/node_modules/@babel/generator/lib/source-map.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}
```

Versions:
- Node 18.15.0
- Yarn 1.17.3
- react-native 0.68.2
- @babel/core 7.12.9
- @babel/runtime 7.12.5

package.json
```
{
  "name": "project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start --reset-cache",
    "start:local": "dotenv -e .env.local react-native start --reset-cache",
    "start:development": "react-native start",
    "start:production": "react-native start",
    "test": "jest",
    "lint": "eslint",
    "init-data": "sh -ac 'REACT_APP_ENV=local; . ./.env.${REACT_APP_ENV}; node ./scripts/initData.js'",
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@miblanchard/react-native-slider": "^2.2.0",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/auth": "^14.11.0",
    "@react-native-firebase/firestore": "^14.11.0",
    "@react-native-firebase/storage": "^14.11.0",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-navigation/core": "^6.2.1",
    "@react-navigation/material-top-tabs": "^6.5.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "algoliasearch": "^4.14.1",
    "babel-plugin-inline-import": "^3.0.0",
    "deepmerge": "^4.2.2",
    "dotenv-cli": "^6.0.0",
    "faker": "^4.1.0",
    "firebase-admin": "^11.4.1",
    "getstream": "^8.1.0",
    "lodash": "^4.17.21",
    "metro-config": "^0.74.0",
    "react": "17.0.2",
    "react-instantsearch-hooks": "^6.30.2",
    "react-native": "0.68.2",
    "react-native-activity-feed": "1.1.0",
    "react-native-activity-feed-core": "^1.1.1",
    "react-native-dotenv": "^3.3.1",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-image-crop-picker": "^0.35.2",
    "react-native-image-picker": "^4.8.4",
    "react-native-pager-view": "^6.1.2",
    "react-native-paper": "5.0.0-rc.2",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.18.2",
    "react-native-segmented-control-tab": "^4.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^13.7.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.3.4",
    "react-native-text-input-interactive": "^0.1.3",
    "react-native-vector-icons": "^9.1.0",
    "react-navigation": "^4.4.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "prettier": "^2.7.1",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by jridgewell** [comment]
Everything I can find online about this says it's an issue with the node install. I would uninstall whatever node version and version manager you're using, and reinstall.

Closing, since this isn't directly related to gen-mapping (and there aren't any other reports to indicate it is).
